"use client";import { useMemo,useState } from "react";import { useRouter } from "next/navigation";import Link from "next/link";import { Plus,Search,X } from "lucide-react";import { formatCurrency,formatDate } from "@/lib/utils";
type P={id:string;name:string;description:string|null;budget:number;deadline:Date|string|null;progress:number;status:string;client:{id:string;name:string}|null};type C={id:string;name:string};
export function ProjectManager({initial,clients}:{initial:P[];clients:C[]}){const[items,setItems]=useState(initial);const[q,setQ]=useState("");const[status,setStatus]=useState("ALL");const[open,setOpen]=useState(false);const router=useRouter();const filtered=useMemo(()=>items.filter(x=>(status==="ALL"||x.status===status)&&`${x.name} ${x.client?.name||""}`.toLowerCase().includes(q.toLowerCase())),[items,q,status]);async function create(fd:FormData){const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});const j=await r.json();if(r.ok){setOpen(false);router.refresh()}else alert(j.error)}return <><div className="mb-5 flex flex-wrap gap-3"><div className="relative max-w-md flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input" style={{paddingLeft:"40px"}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects..."/></div><div className="w-full sm:w-52"><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="PLANNING">Planning</option><option value="IN_PROGRESS">In Progress</option><option value="REVIEW">Review</option><option value="COMPLETED">Completed</option><option value="ON_HOLD">On Hold</option></select></div><button className="btn-primary whitespace-nowrap" onClick={()=>setOpen(true)}><Plus size={17}/>New Project</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><Link key={p.id} href={`/dashboard/projects/${p.id}`} className="card group p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><div><p className="text-lg font-black group-hover:text-indigo-600">{p.name}</p><p className="text-sm text-slate-500">{p.client?.name||"Internal project"}</p></div><span className={`badge ${
p.status==="COMPLETED" ? "bg-emerald-50 text-emerald-700" :
p.status==="IN_PROGRESS" ? "bg-blue-50 text-blue-700" :
p.status==="REVIEW" ? "bg-amber-50 text-amber-700" :
p.status==="ON_HOLD" ? "bg-red-50 text-red-700" :
"bg-violet-50 text-violet-700"
}`}>{p.status.replaceAll("_"," ")}</span></div><p className="mt-5 line-clamp-2 min-h-10 text-sm text-slate-500">{p.description||"No description added."}</p><div className="mt-5 flex justify-between text-xs font-bold text-slate-500"><span>{formatCurrency(p.budget)}</span><span className={p.deadline && new Date(p.deadline) < new Date() && p.status !== "COMPLETED" ? "text-red-600" : p.status === "COMPLETED" ? "text-emerald-600" : "text-slate-500"}>Due {formatDate(p.deadline)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{width:`${p.progress}%`}}/></div><p className="mt-2 text-right text-xs font-black text-indigo-600">{p.progress}%</p></Link>)}{!filtered.length&&<div className="card col-span-full grid min-h-52 place-items-center text-slate-400">No projects found.</div>}</div>{open&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="card w-full max-w-2xl p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Create Project</h2><p className="text-sm text-slate-500">Plan client work, budget and delivery dates.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><form action={create} className="mt-6 grid gap-4 sm:grid-cols-2"><F n="name" l="Project name" req/><label><span className="label">Client</span><select name="clientId" className="input"><option value="">Internal / none</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><F n="budget" l="Budget" type="number"/><label><span className="label">Status</span><select className="input" name="status">{["PLANNING","IN_PROGRESS","REVIEW","COMPLETED","ON_HOLD"].map(s=><option key={s}>{s}</option>)}</select></label><F n="startDate" l="Start date" type="date"/><F n="deadline" l="Deadline" type="date"/><label className="sm:col-span-2"><span className="label">Description</span><textarea className="input min-h-24" name="description"/></label><div className="sm:col-span-2 flex justify-end"><button className="btn-primary">Create Project</button></div></form></div></div>}</>}
function F({n,l,type="text",req=false}:{n:string;l:string;type?:string;req?:boolean}){return <label><span className="label">{l}</span><input className="input" name={n} type={type} required={req}/></label>}





