import Link from "next/link";
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, CircleDollarSign, ContactRound, KanbanSquare, ListTodo, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/logo";

const features = [
  [ContactRound,"Client Management","Keep every contact, note, project and invoice connected in one polished workspace."],
  [KanbanSquare,"Lead Pipeline","Move opportunities through a visual sales pipeline and convert wins into clients."],
  [BriefcaseBusiness,"Project Tracking","Track budgets, deadlines, progress and client work without switching tools."],
  [ListTodo,"Smart Tasks","Prioritize work by urgency, project and due date with focused task views."],
  [CircleDollarSign,"Invoices","Create professional invoices, calculate totals automatically and export PDF files."],
  [BarChart3,"Analytics","Understand revenue, conversion, project health and client growth at a glance."],
];

export default function Home() {
  return <main className="min-h-screen bg-white text-slate-950">
    <nav className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Logo/><div className="hidden items-center gap-8 text-sm font-semibold text-slate-600 md:flex"><a href="#features">Features</a><a href="#solutions">Solutions</a><a href="#pricing">Pricing</a></div><div className="flex items-center gap-2"><Link href="/login" className="btn-secondary">Sign In</Link><Link href="/register" className="btn-primary">Get Started <ArrowRight size={16}/></Link></div></div>
    </nav>
    <section className="overflow-hidden bg-[radial-gradient(circle_at_top,#eef2ff_0,white_45%)]">
      <div className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-24 lg:grid-cols-[1fr_1.05fr] lg:py-32">
        <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1.5 text-sm font-bold text-indigo-700"><Sparkles size={15}/> Built for focused client work</div><h1 className="max-w-3xl text-5xl font-black leading-[1.04] tracking-[-.05em] md:text-7xl">Manage Clients.<br/>Close Deals. <span className="text-indigo-600">Get Paid.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">ClientFlow brings your CRM, sales pipeline, projects, tasks, invoices and business analytics into one clean workspace designed for freelancers, agencies and small teams.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="btn-primary px-5 py-3">Start for Free <ArrowRight size={17}/></Link><Link href="/login?demo=1" className="btn-secondary px-5 py-3">View Demo</Link></div><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><Check size={16} className="text-emerald-500"/>No card required</span><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-indigo-500"/>Data isolated per workspace</span></div></div>
        <div className="relative"><div className="absolute -inset-10 -z-10 rounded-full bg-indigo-200/40 blur-3xl"/><div className="overflow-hidden rounded-[28px] border border-slate-200 bg-slate-950 p-2 shadow-2xl shadow-indigo-200"><div className="rounded-[22px] bg-[#f7f8fb] p-4"><div className="mb-4 flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-400"/><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><div className="grid gap-3 md:grid-cols-3">{[["Revenue","$48.2k","+18.4%"],["Clients","128","+12"],["Pipeline","$93k","24 deals"]].map(x=><div key={x[0]} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-500">{x[0]}</p><p className="mt-2 text-2xl font-black">{x[1]}</p><p className="mt-1 text-xs font-bold text-emerald-600">{x[2]}</p></div>)}</div><div className="mt-3 grid gap-3 md:grid-cols-[1.4fr_.8fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="font-bold">Monthly revenue</p><div className="mt-8 flex h-40 items-end gap-3">{[38,52,45,68,74,62,86,92].map((h,i)=><div key={i} className="flex-1 rounded-t-lg bg-gradient-to-t from-indigo-600 to-indigo-300" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="font-bold">Project status</p><div className="mx-auto mt-6 grid h-36 w-36 place-items-center rounded-full bg-[conic-gradient(#4f46e5_0_55%,#818cf8_55%_78%,#e0e7ff_78%)]"><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><span className="text-2xl font-black">32</span></div></div></div></div></div></div></div>
      </div>
    </section>
    <section id="features" className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.2em] text-indigo-600">Everything connected</p><h2 className="mt-3 text-4xl font-black tracking-tight">One operating system for client work.</h2><p className="mt-4 text-slate-600">Replace scattered spreadsheets and disconnected tools with a workflow that keeps sales, delivery and cash flow aligned.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text]:any)=><div key={title} className="rounded-3xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-200/50"><div className="mb-5 grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Icon size={21}/></div><h3 className="text-lg font-extrabold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></div>)}</div></section>
    <section id="solutions" className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.2em] text-indigo-300">How it works</p><h2 className="mt-3 text-4xl font-black">From first lead to final invoice.</h2></div><div className="grid gap-4">{["Capture leads and qualify opportunities","Convert wins into structured client records","Deliver projects with tasks, budgets and deadlines","Send professional invoices and monitor cash flow"].map((x,i)=><div key={x} className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-indigo-500 font-black">{i+1}</span><p className="font-semibold text-slate-200">{x}</p></div>)}</div></div></div></section>
    <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-indigo-600">Loved by focused teams</p><h2 className="mt-3 text-4xl font-black">Less admin. More momentum.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["ClientFlow replaced three spreadsheets and finally gave me a clear picture of what is due, what is paid and what needs attention.","Maya Chen","Independent Consultant"],["The pipeline-to-project workflow feels like software built for a small agency instead of an enterprise CRM cut down to size.","Daniel Foster","Studio Founder"],["Clean enough to use every day, but deep enough to track the client details and invoice status our team actually cares about.","Sara Malik","Creative Director"]].map(([quote,name,role])=><figure key={name} className="rounded-3xl border border-slate-200 bg-white p-6"><blockquote className="text-base font-semibold leading-7 text-slate-700">“{quote}”</blockquote><figcaption className="mt-6"><p className="font-black">{name}</p><p className="text-sm text-slate-500">{role}</p></figcaption></figure>)}</div></div></section>
    <section id="pricing" className="mx-auto max-w-7xl px-6 py-24"><div className="text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-indigo-600">Demo pricing</p><h2 className="mt-3 text-4xl font-black">Simple plans that scale with you.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[["Starter","$0","For solo freelancers",["50 clients","Core CRM","Tasks & projects"]],["Professional","$24","For growing consultants",["Unlimited clients","Analytics","Invoice PDF exports"]],["Agency","$59","For small teams",["Everything in Pro","Advanced reporting","Priority support"]]].map((p,i)=><div key={p[0] as string} className={`rounded-3xl border p-7 ${i===1?'border-indigo-500 bg-indigo-50 shadow-xl shadow-indigo-100':'border-slate-200'}`}><p className="text-lg font-extrabold">{p[0] as string}</p><p className="mt-4 text-4xl font-black">{p[1] as string}<span className="text-sm font-semibold text-slate-500">/mo</span></p><p className="mt-2 text-slate-600">{p[2] as string}</p><div className="my-6 h-px bg-slate-200"/>{(p[3] as string[]).map(x=><p key={x} className="mb-3 flex items-center gap-2 text-sm font-semibold"><Check size={16} className="text-emerald-500"/>{x}</p>)}<Link href="/register" className={`mt-4 w-full ${i===1?'btn-primary':'btn-secondary'}`}>Get Started</Link></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24"><div className="rounded-[32px] bg-gradient-to-br from-indigo-600 to-violet-700 px-8 py-14 text-center text-white shadow-2xl shadow-indigo-200"><h2 className="text-4xl font-black">Build stronger client relationships today.</h2><p className="mx-auto mt-4 max-w-2xl text-indigo-100">A portfolio-grade SaaS experience with the workflows a real service business needs.</p><Link href="/register" className="mt-7 inline-flex items-center justify-center rounded-xl bg-white px-6 py-3 font-black !text-indigo-700 transition hover:-translate-y-0.5 hover:bg-indigo-50">Create your workspace</Link></div></section>
    <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-6 py-10 md:flex-row md:items-center md:justify-between"><Logo/><p className="text-sm text-slate-500">© 2026 ClientFlow. Built as a modern full-stack SaaS CRM.</p></div></footer>
  </main>;
}
